use Warehouse
go

DBCC CHECKIDENT ('dbo.TEACHER', RESEED, 0);
DBCC CHECKIDENT ('dbo.DATE', RESEED, 0);
DBCC CHECKIDENT ('dbo.Time', RESEED, 0);
DBCC CHECKIDENT ('dbo.STUDENT', RESEED, 0);
DBCC CHECKIDENT ('dbo.OFFER', RESEED, 0);
