USE Warehouse
GO

-- Wyłączenie sprawdzania kluczy obcych
ALTER TABLE CLASSRUN NOCHECK CONSTRAINT ALL;
ALTER TABLE OFFER NOCHECK CONSTRAINT ALL;
ALTER TABLE STUDENT NOCHECK CONSTRAINT ALL;
ALTER TABLE TEACHER NOCHECK CONSTRAINT ALL;
ALTER TABLE TIME NOCHECK CONSTRAINT ALL;
ALTER TABLE DATE NOCHECK CONSTRAINT ALL;

-- Usuwanie danych
DELETE FROM CLASSRUN;
DELETE FROM OFFER;
DELETE FROM STUDENT;
DELETE FROM TEACHER;
DELETE FROM TIME;
DELETE FROM DATE;

-- Ponowne włączenie sprawdzania kluczy obcych
ALTER TABLE CLASSRUN CHECK CONSTRAINT ALL;
ALTER TABLE OFFER CHECK CONSTRAINT ALL;
ALTER TABLE STUDENT CHECK CONSTRAINT ALL;
ALTER TABLE TEACHER CHECK CONSTRAINT ALL;
ALTER TABLE TIME CHECK CONSTRAINT ALL;
ALTER TABLE DATE CHECK CONSTRAINT ALL;

-- -- Usuwanie tabel
DROP TABLE IF EXISTS CLASSRUN;
DROP TABLE IF EXISTS OFFER;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS TIME;
DROP TABLE IF EXISTS DATE;

